apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: dev
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
      annotations:
        secret-version: "v2"
    spec:
      initContainers:
        - name: inject-secrets
          image: busybox
          command: ['sh', '-c']
          args:
            - |
              cp /template/index.html /usr/share/nginx/html/index.html
              sed -i "s|SECRET_MESSAGE_PLACEHOLDER|${SECRET_MESSAGE}|g" /usr/share/nginx/html/index.html
              MASKED_KEY=$(echo "$API_KEY" | sed 's/.\{5\}$/xxxxx/')
              sed -i "s|API_KEY_PLACEHOLDER|${MASKED_KEY}|g" /usr/share/nginx/html/index.html
          env:
            - name: SECRET_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: MESSAGE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: hello-secret
                  key: API_KEY
          volumeMounts:
            - name: template
              mountPath: /template
            - name: html
              mountPath: /usr/share/nginx/html
      containers:
        - name: hello
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: template
          configMap:
            name: hello-page
        - name: html
          emptyDir: {}